name: build-windows
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # build on version tags
jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run dist:win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/**
